/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DeepSpeechCaller */

#ifndef _Included_DeepSpeechCaller
#define _Included_DeepSpeechCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DeepSpeechCaller
 * Method:    DS_Version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_DeepSpeechCaller_DS_1Version
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
