/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_NativeInterface_NativeInterface */

#ifndef _Included_com_NativeInterface_NativeInterface
#define _Included_com_NativeInterface_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_NativeInterface_NativeInterface
 * Method:    DS_Version
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_NativeInterface_NativeInterface_DS_1Version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
