/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DeepSpeechCaller */

#ifndef _Included_DeepSpeechCaller
#define _Included_DeepSpeechCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DeepSpeechCaller
 * Method:    Version
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DeepSpeechCaller_Version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
